### ISSUE TITLE
Tracking: Alpha 1 Release

### ISSUE THREAD

**Issue by sgammon** [elide-dev/v3#10]
Tracking ticket for initial release.

- [x] Basic samples
- [x] README
- [x] Docker images for base, samples, codespace
- [x] Docs site & domain
- [x] Early major functionality
  - [x] #11 (filed as #9)
  - [x] #14 (filed as #22)
  - [x] #34
- [x] Basic stuff
  - [x] Presets for Micronaut config
  - [x] Error handlers
- [x] Dev Experience
  - [x] Published API docs
  - [x] #65
  - [x] #69 
  - [x] #70
  - [x] #71
  - [x] ~~#72~~
  - [x] #73
  - [x] ~~#74~~
  - [x] ~~#75~~
  - [x] #76
  - [x] #77
  - [x] ~~#78~~
  - [x] ~~#79~~
  - [x] #80
- [x] Known issues
  - [x] #35
  - [x] #36
  - [x] #80
